/**
 * Generate Arabic translations from English
 * Strategy: Copy English structure, translate critical UI strings to Arabic,
 * keep English fallback for less-critical strings to prevent MISSING_MESSAGE crashes
 */
const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'frontend', 'messages', 'en.json');
const arPath = path.join(__dirname, '..', 'frontend', 'messages', 'ar.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Critical Arabic translations for common UI elements
const translations = {
  nav: {
    home: 'الرئيسية',
    restaurant: 'المطعم',
    chalets: 'الشاليهات',
    pool: 'المسبح',
    snackBar: 'مقصف الوجبات الخفيفة',
    giftCards: 'بطاقات الهدايا',
    loyalty: 'برنامج الولاء',
    contact: 'اتصل بنا',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    cart: 'السلة',
    admin: 'لوحة الإدارة',
    staff: 'لوحة الموظفين',
    menu: 'القائمة',
    reservations: 'الحجوزات',
    orders: 'الطلبات',
    bookings: 'الحجوزات',
    settings: 'الإعدادات',
    about: 'من نحن',
    back: 'رجوع',
    viewAll: 'عرض الكل',
  },
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    confirm: 'تأكيد',
    close: 'إغلاق',
    yes: 'نعم',
    no: 'لا',
    submit: 'إرسال',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    refresh: 'تحديث',
    noResults: 'لا توجد نتائج',
    actions: 'إجراءات',
    status: 'الحالة',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    date: 'التاريخ',
    time: 'الوقت',
    price: 'السعر',
    total: 'المجموع',
    subtotal: 'المجموع الفرعي',
    quantity: 'الكمية',
    description: 'الوصف',
    details: 'التفاصيل',
    view: 'عرض',
    create: 'إنشاء',
    update: 'تحديث',
    remove: 'إزالة',
    all: 'الكل',
    active: 'نشط',
    inactive: 'غير نشط',
    enabled: 'مفعل',
    disabled: 'معطل',
    available: 'متاح',
    unavailable: 'غير متاح',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    confirmed: 'مؤكد',
    cancelled: 'ملغى',
    today: 'اليوم',
    yesterday: 'أمس',
    tomorrow: 'غداً',
    currency: 'العملة',
    language: 'اللغة',
    theme: 'المظهر',
    dark: 'داكن',
    light: 'فاتح',
    system: 'النظام',
    or: 'أو',
    and: 'و',
    of: 'من',
    to: 'إلى',
    from: 'من',
    items: 'عناصر',
    item: 'عنصر',
    copy: 'نسخ',
    copied: 'تم النسخ',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    print: 'طباعة',
    share: 'مشاركة',
    more: 'المزيد',
    less: 'أقل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    seeAll: 'مشاهدة الكل',
    viewDetails: 'عرض التفاصيل',
    selectAll: 'تحديد الكل',
    clearAll: 'مسح الكل',
    sortBy: 'ترتيب حسب',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    required: 'مطلوب',
    optional: 'اختياري',
    featured: 'مميز',
    popular: 'شائع',
    new: 'جديد',
    free: 'مجاني',
    off: 'خصم',
    perNight: 'لليلة',
    perPerson: 'للشخص',
    guests: 'ضيوف',
    adults: 'بالغين',
    children: 'أطفال',
    checkIn: 'تسجيل الوصول',
    checkOut: 'تسجيل المغادرة',
    nights: 'ليالي',
    roomType: 'نوع الغرفة',
    addToCart: 'أضف إلى السلة',
    removeFromCart: 'إزالة من السلة',
    goToCart: 'الذهاب إلى السلة',
    checkout: 'الدفع',
    placeOrder: 'تقديم الطلب',
    orderNow: 'اطلب الآن',
    bookNow: 'احجز الآن',
    buyNow: 'اشتري الآن',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    retry: 'إعادة المحاولة',
    note: 'ملاحظة',
    notes: 'ملاحظات',
    address: 'العنوان',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثوانٍ',
    days: 'أيام',
    weeks: 'أسابيع',
    months: 'أشهر',
    years: 'سنوات',
  },
  auth: {
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    rememberMe: 'تذكرني',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signInWith: 'تسجيل الدخول بواسطة',
    orContinueWith: 'أو تابع بواسطة',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    createAccount: 'إنشاء حساب جديد',
    welcomeBack: 'مرحباً بعودتك',
    loginSubtitle: 'سجل الدخول للوصول إلى حسابك',
    registerSubtitle: 'أنشئ حسابك للبدء',
    demoCredentials: 'بيانات تجريبية',
    backToHome: 'العودة إلى الصفحة الرئيسية',
  },
  settings: {
    title: 'الإعدادات',
    language: 'اللغة',
    theme: 'المظهر',
    currency: 'العملة',
    preferences: 'التفضيلات',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    systemMode: 'وضع النظام',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
  },
  footer: {
    quickLinks: 'روابط سريعة',
    legal: 'قانوني',
    contact: 'اتصل بنا',
    copyright: '© 2026 جميع الحقوق محفوظة.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    cancellationPolicy: 'سياسة الإلغاء',
  },
  admin: {
    nav: {
      dashboard: 'لوحة التحكم',
      modules: 'الوحدات',
      marketing: 'التسويق',
      operations: 'العمليات',
      people: 'الأشخاص',
      system: 'النظام',
      loyalty: 'برنامج الولاء',
      giftCards: 'بطاقات الهدايا',
      coupons: 'القسائم',
      reviews: 'المراجعات',
      housekeeping: 'التدبير المنزلي',
      inventory: 'المخزون',
      users: 'المستخدمين',
      reports: 'التقارير',
      settings: 'الإعدادات',
      auditLogs: 'سجلات التدقيق',
      logout: 'تسجيل الخروج',
    },
    dashboard: {
      title: 'لوحة التحكم',
      welcomeBack: 'مرحباً بعودتك',
      onlineUsers: 'المستخدمون المتصلون',
      todaysOrders: 'طلبات اليوم',
      todaysRevenue: 'إيرادات اليوم',
      activeBookings: 'الحجوزات النشطة',
      recentOrders: 'الطلبات الأخيرة',
      quickActions: 'إجراءات سريعة',
      revenueByUnit: 'الإيرادات حسب الوحدة',
      refresh: 'تحديث',
    },
  },
  adminCommon: {
    menu: {
      items: 'عناصر القائمة',
      categories: 'التصنيفات',
      manageMenu: 'إدارة القائمة',
      addOrEdit: 'إضافة أو تعديل العناصر',
      organizeMenu: 'تنظيم القائمة',
    },
    orders: {
      title: 'الطلبات',
      viewAndManage: 'عرض وإدارة الطلبات',
    },
  },
  restaurant: {
    title: 'المطعم',
    menu: 'القائمة',
    ourMenu: 'قائمتنا',
    featuredDishes: 'أطباق مميزة',
    categories: 'التصنيفات',
    addToCart: 'أضف إلى السلة',
    viewMenu: 'عرض القائمة',
    orderNow: 'اطلب الآن',
    specialInstructions: 'تعليمات خاصة',
    customize: 'تخصيص',
    dietary: {
      vegetarian: 'نباتي',
      vegan: 'نباتي صرف',
      glutenFree: 'خالٍ من الغلوتين',
      spicy: 'حار',
    },
  },
  home: {
    hero: {
      title: 'مرحباً بكم في منتجعنا',
      subtitle: 'اكتشف تجربة فاخرة لا مثيل لها',
      cta: 'استكشف الآن',
    },
    features: 'المميزات',
    services: 'الخدمات',
    about: 'من نحن',
    testimonials: 'آراء العملاء',
  },
  contact: {
    title: 'اتصل بنا',
    subtitle: 'نحن هنا لمساعدتك',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    subject: 'الموضوع',
    message: 'الرسالة',
    send: 'إرسال',
    success: 'تم إرسال رسالتك بنجاح!',
    businessHours: 'ساعات العمل',
  },
  legal: {
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    cancellationPolicy: 'سياسة الإلغاء',
    backToHome: 'العودة إلى الصفحة الرئيسية',
  },
  weather: {
    title: 'الطقس',
    temperature: 'درجة الحرارة',
    humidity: 'الرطوبة',
  },
  profile: {
    title: 'الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    myOrders: 'طلباتي',
    myBookings: 'حجوزاتي',
    myTickets: 'تذاكري',
    preferences: 'التفضيلات',
    security: 'الأمان',
    twoFactor: 'التحقق بخطوتين',
  },
  staff: {
    dashboard: 'لوحة الموظفين',
    kitchen: 'المطبخ',
    orders: 'الطلبات',
    bookings: 'الحجوزات',
    scanner: 'الماسح الضوئي',
    customers: 'العملاء',
    manager: 'المدير',
  },
  staffScanner: {
    title: 'ماسح التذاكر',
    scan: 'مسح',
    enterCode: 'أدخل الرمز',
    valid: 'صالح',
    invalid: 'غير صالح',
    recentScans: 'عمليات المسح الأخيرة',
  },
  payment: {
    title: 'الدفع',
    method: 'طريقة الدفع',
    cash: 'نقداً',
    card: 'بطاقة',
    stripe: 'Stripe',
    total: 'المجموع',
    pay: 'ادفع',
    processing: 'جاري المعالجة...',
    success: 'تمت عملية الدفع بنجاح!',
    failed: 'فشلت عملية الدفع',
  },
  wishlist: {
    title: 'قائمة الأمنيات',
    empty: 'قائمة أمنياتك فارغة',
    add: 'أضف إلى قائمة الأمنيات',
    remove: 'إزالة من قائمة الأمنيات',
    clearAll: 'مسح الكل',
    exploreNow: 'استكشف الآن',
  },
  chat: {
    title: 'الدردشة',
    sendMessage: 'إرسال رسالة',
    online: 'متصل',
    offline: 'غير متصل',
  },
};

// Deep merge: use Arabic where available, English as fallback
function deepMerge(enObj, arOverrides) {
  const result = {};
  for (const key of Object.keys(enObj)) {
    if (arOverrides && key in arOverrides) {
      if (typeof enObj[key] === 'object' && enObj[key] !== null && typeof arOverrides[key] === 'object' && arOverrides[key] !== null) {
        result[key] = deepMerge(enObj[key], arOverrides[key]);
      } else {
        result[key] = arOverrides[key];
      }
    } else if (typeof enObj[key] === 'object' && enObj[key] !== null) {
      result[key] = deepMerge(enObj[key], null);
    } else {
      // Keep English as fallback - better than MISSING_MESSAGE
      result[key] = enObj[key];
    }
  }
  return result;
}

const ar = deepMerge(en, translations);
fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');

const arSize = fs.statSync(arPath).size;
console.log(`Generated ar.json: ${(arSize / 1024).toFixed(1)}KB`);
console.log(`Translated ${Object.keys(translations).length} top-level sections to Arabic`);
console.log(`All other keys use English as fallback (no more MISSING_MESSAGE errors)`);
